language: go
os: "linux"
sudo: true

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x

notifications:
  email: false

install:
  - go get github.com/huzhongqing/simplelog
script:
  - pwd
  - pushd $TRAVIS_BUILD_DIR
  - pwd
  - chmod +x test.sh
  - ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)  